name: guestbook

labels:
  app: guestbook

deployments:
- containers:
  - name: guestbook
    image: gcr.io/google_containers/guestbook:v3
    health:
      httpGet:
        path: /
        port: 3000
      initialDelaySeconds: 20
      timeoutSeconds: 5
 
services:
- name: guestbook
  portMappings: 
  - 3000:3000
  type: NodePort

---

name: redis-master

labels:
  app: redis
  role: master

deployments:
- containers:
  - name: redis-master
    image: redis:2.8.23
  
services:
- name: redis-master
  portMappings: 
  - 6379:6379

---

name: redis-slave

labels:
  app: redis
  role: slave

deployments:
- containers:
  - name: redis-slave
    image: kubernetes/redis-slave:v2

services:
- name: redis-slave
  portMappings: 
  - 6379:6379
